# permissions for end users to edit externalhacontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalhacontroller-editor-role
rules:
- apiGroups:
  - csiplugins.spdbdev.io
  resources:
  - externalhacontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiplugins.spdbdev.io
  resources:
  - externalhacontrollers/status
  verbs:
  - get
