
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - csiplugins.spdbdev.io
  resources:
  - externalhacontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiplugins.spdbdev.io
  resources:
  - externalhacontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - csiplugins.spdbdev.io
  resources:
  - externalhacontrollers/status
  verbs:
  - get
  - patch
  - update
